In [2]:
import tensorflow as tf

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Equation

In [10]:
w=tf.constant(3)
x=w+2

In [4]:
tf.add(w,2)

<tf.Tensor 'Add_1:0' shape=() dtype=int32>

In [6]:
w+2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [18]:
y=tf.Variable(1)

In [7]:
tf.Session()

In [8]:
sess=tf.get_default_session()

In [9]:
print(sess)

None


In [13]:
x=tf.Variable(1)
y=x+x
with tf.Session() as sess:
    sess.run(x.initializer)
    print(y.eval())

2


## reduce_mean

In [15]:
import numpy as np

In [39]:
arr=np.arange(12).reshape(3,4).astype(np.float32)

In [40]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [41]:
m=tf.reduce_mean(arr,1)
print(m)

Tensor("Mean_9:0", shape=(3,), dtype=float32)


In [42]:
with tf.Session() as sess:
    print(m.eval())

[1.5 5.5 9.5]


In [43]:
arr=np.arange(24).reshape(2,3,4).astype(np.float32)

In [44]:
arr

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)

In [45]:
m=tf.reduce_mean(arr,1)
print(m)

Tensor("Mean_10:0", shape=(2, 4), dtype=float32)


In [47]:
with tf.Session() as sess:
    print(m.eval())

[[ 4.  5.  6.  7.]
 [16. 17. 18. 19.]]


In [3]:
tf.placeholder('float')

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [4]:
tf.placeholder(float)

<tf.Tensor 'Placeholder_1:0' shape=<unknown> dtype=float32>

# cross entropy

$
J(\boldsymbol{\Theta}) = - \dfrac{1}{m}\sum\limits_{i=1}^{m}\sum\limits_{k=1}^{K}{y_k^{(i)}\log\left(\hat{p}_k^{(i)}\right)}
$  
natural logarithm

In [3]:
import numpy as np

In [8]:
y=np.array([0,1,2])
logits=np.array([[2,1,0],[1,2,0],[0,1,2]]).astype(np.float)
entropy=tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,logits=logits)
loss=tf.reduce_mean(entropy)

In [9]:
with tf.Session() as sess:
    print(entropy.eval())
    print(loss.eval())

[0.40760596 0.40760596 0.40760596]
0.4076059644443804


$1\cdot ln\dfrac{e^2}{e^2+e^1+e^0}=0.40760596$

# calculation

In [4]:
n_inputs=8
X=tf.Variable(tf.ones((1,n_inputs)))
W=tf.Variable(tf.truncated_normal([n_inputs,10]))
b=tf.Variable(tf.ones(10))

In [5]:
z=tf.matmul(X,W)+b

In [8]:
init=tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    print(X.eval(),'\n')
    print(tf.matmul(X,W).eval(),'\n')
    print(b.eval(),'\n')
    print(z.eval())

[[1. 1. 1. 1. 1. 1. 1. 1.]] 

[[-0.86947906  1.1617016  -0.07864641  3.889629   -0.9031818   2.3256671
  -1.7303421   0.7513348  -1.9287752  -1.2880555 ]] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[ 0.13052094  2.1617017   0.9213536   4.889629    0.09681821  3.3256671
  -0.73034215  1.7513348  -0.9287752  -0.28805554]]


# argmax

In [10]:
import numpy as np
arr=np.array([[1,2,3],[2,4,1],[5,4,1]])
print(np.argmax(arr,axis=1))

[2 1 0]


# Batch Normalization

In [1]:
import tensorflow as tf

D:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [10]:
img = tf.Variable(tf.random_normal([2, 3]))
mean, variance = tf.nn.moments(img, [0])

In [12]:
init=tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    print(img.eval())
    print('mean:',mean.eval())
    print('variance:',variance.eval())

[[ 0.71340865 -2.269372    0.31259796]
 [-0.1965941   0.09043169  0.12165551]]
mean: [ 0.25840726 -1.0894701   0.21712673]
variance: [0.20702624 1.3921684  0.00911476]


# DNN

# Keras

In [13]:
#https://tensorflow.google.cn/tutorials/
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

Epoch 1/5
60000/60000 [==============================] - 20s 331us/step - loss: 0.2170 - acc: 0.9364
Epoch 2/5
60000/60000 [==============================] - 20s 327us/step - loss: 0.0970 - acc: 0.9702
Epoch 3/5
60000/60000 [==============================] - 20s 330us/step - loss: 0.0683 - acc: 0.9777
Epoch 4/5
60000/60000 [==============================] - 20s 334us/step - loss: 0.0540 - acc: 0.9825
Epoch 5/5
10000/10000 [==============================] - 1s 62us/step


[0.07672003290665452, 0.9777]